/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 211e936360c82271667001d852f31f5a)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
